# Generated by Django 2.1.7 on 2019-04-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Channel Name')),
                ('value', models.SmallIntegerField(unique=True, verbose_name='Channel Value')),
                ('logo', models.ImageField(blank=True, upload_to='channel_logo', verbose_name='Channel Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_start', models.TimeField(verbose_name='Recording Start Time')),
                ('rec_stop', models.TimeField(verbose_name='Recording Stop Time')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule_api.Channel', verbose_name='Channel Name')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B')], default=0, verbose_name='Device ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Node', verbose_name='Node')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.Schedule', verbose_name='Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='nodes',
            field=models.ManyToManyField(through='schedule_api.ScheduleNode', to='monitoring.Node'),
        ),
    ]
