# Generated by Django 2.1.7 on 2019-04-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B')], default=0, verbose_name='Device ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Node', verbose_name='Node')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedulenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='schedulenode',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='nodes',
            field=models.ManyToManyField(through='schedule_api.NodeAllocation', to='monitoring.Node'),
        ),
        migrations.DeleteModel(
            name='ScheduleNode',
        ),
        migrations.AddField(
            model_name='nodeallocation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.Schedule', verbose_name='Schedule'),
        ),
    ]
