# Generated by Django 2.1.7 on 2019-04-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='device_id',
            new_name='device',
        ),
    ]
