# Generated by Django 2.1.7 on 2019-04-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0002_auto_20190426_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeallocation',
            name='label',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Device ID'),
        ),
    ]
