image: ubuntu

pages:
  script:
  - apt-get update
  - apt-get install libmysqlclient-dev python3-pip -y #(dependency for pip mysqlclient)
  - pip3 install -r requirements.txt
  - cd docs
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - feature-monitoring
