image: python:3.6-alpine

pages:
  script:
  - apk add libmysqlclient-dev
  - pip install -r requirements.txt
  - cd docs
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - feature-monitoring
