image: ubuntu

pages:
  script:
  - sudo apt install libmysqlclient-dev #(dependency for pip mysqlclient)
  - sudo apt install python3-pip
  - pip3 install -r requirements.txt
  - cd docs
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - feature-monitoring
