# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-30 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190127_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='filterrecordingtracking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invalidframetracking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recordingtracking',
            options={'managed': False},
        ),
    ]
