# Generated by Django 2.1.7 on 2019-03-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('username', models.CharField(default='user', max_length=50, verbose_name='SSH Username')),
                ('password', models.CharField(default='12345', max_length=100, verbose_name='SSH Password')),
                ('mac_address', models.CharField(blank=True, max_length=20, verbose_name='MAC Address')),
                ('screenshot', models.ImageField(blank=True, upload_to='screenshots', verbose_name='Last Screenshot')),
            ],
        ),
    ]
