# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_value', models.IntegerField(blank=True, null=True)),
                ('channel_name', models.TextField(blank=True, null=True)),
                ('parent_network', models.TextField(blank=True, null=True)),
                ('market', models.TextField(blank=True, null=True)),
                ('channel_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilterRecordingTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True, null=True)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('channel_value', models.IntegerField(blank=True, null=True)),
                ('clip_path', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('start_timestamp', models.TextField(blank=True, null=True)),
                ('end_timestamp', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('clip_slot', models.TextField(blank=True, null=True)),
                ('clip_number', models.IntegerField(blank=True, null=True)),
                ('clip_size', models.FloatField(blank=True, null=True)),
                ('clip_duration', models.FloatField(blank=True, null=True)),
                ('prediction_status', models.TextField(blank=True, null=True)),
                ('blank_flag', models.TextField(blank=True, null=True)),
                ('corrupt_flag', models.TextField(blank=True, null=True)),
                ('character_status', models.TextField(blank=True, null=True)),
                ('toprocess', models.TextField(blank=True, db_column='toProcess', null=True)),
            ],
            options={
                'db_table': 'filter_recording_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvalidFrameTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True, null=True)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('invalid_frame_from', models.FloatField(blank=True, null=True)),
                ('invalid_frame_to', models.FloatField(blank=True, null=True)),
                ('migration_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invalid_frame_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True, null=True)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('channel_value', models.IntegerField(blank=True, null=True)),
                ('stage_number', models.FloatField(blank=True, null=True)),
                ('stage_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
                ('video_path', models.TextField(blank=True, null=True)),
                ('clip_number', models.IntegerField(blank=True, null=True)),
                ('clip_slot', models.TextField(blank=True, null=True)),
                ('migration_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recording',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordingTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True, null=True)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('channel_value', models.IntegerField(blank=True, null=True)),
                ('clip_path', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('start_timestamp', models.TextField(blank=True, null=True)),
                ('end_timestamp', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('clip_slot', models.TextField(blank=True, null=True)),
                ('clip_number', models.IntegerField(blank=True, null=True)),
                ('clip_size', models.TextField(blank=True, null=True)),
                ('clip_duration', models.TextField(blank=True, null=True)),
                ('migration_status', models.IntegerField(blank=True, null=True)),
                ('prediction_status', models.TextField(blank=True, null=True)),
                ('blank_flag', models.TextField(blank=True, null=True)),
                ('corrupt_flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recording_tracking',
                'managed': False,
            },
        ),
    ]
