# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-27 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filterrecordingtracking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invalidframetracking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recordingtracking',
            options={},
        ),
    ]
