# Generated by Django 2.1.7 on 2019-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_system_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='os',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Windows'), (1, 'Linux'), (2, 'Mac OS')], default=1, verbose_name='Operating System'),
        ),
    ]
